import type { Metadata } from "next";
import { TRPCProvider } from "@/trpc/client";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { OfflineOverlay } from "@/modules/videos/ui/components/offline-overlay";


export const metadata: Metadata = {
  title: "YouTube",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body
          className="font-sans"
        >
          <TRPCProvider>
            <Toaster />
            <OfflineOverlay/>
            {children}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
