import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {TRPCProvider} from "@/trpc/client";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "YouTube",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider afterSignOutUrl="/">
    <html lang="en">
      <body
        className={inter.className}
      >
        <TRPCProvider>
          <Toaster/>
        {children}
        </TRPCProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}
